language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

dist: trusty

git:
  depth: 5

notifications:
  email:
    on_success: never
    on_failure: change

branches:
  only:
    - master
    
cache:
  - composer
  - $HOME/.composer/cache

env:
  - WP_PROJECT_TYPE=plugin WP_VERSION=latest WP_MULTISITE=0 WP_TEST_URL=http://localhost:12000 WP_TEST_USER=test WP_TEST_USER_PASS=test

matrix:
  include:
    - php: 7.2
      env: WP_VERSION=latest
    - php: 7.1
      env: WP_VERSION=latest
    - php: 7.0
      env: WP_VERSION=latest
    - php: 5.6
      env: WP_VERSION=4.4
    - php: 5.6
      env: WP_VERSION=latest
    - php: 5.6
      env: WP_VERSION=trunk
    - php: hhvm
      env: WP_VERSION=latest
    - php: nightly
      env: WP_VERSION=latest
  allow_failures:
    - php: nightly

before_script:
  - export PATH="./vendor/bin:$PATH"
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-source --dev
  - |
    if [[ ! -z "$WP_VERSION" ]] ; then
      bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
    fi

script:
  - |
    if [[ ! -z "$WP_VERSION" ]] ; then
      phpunit --coverage-clover=coverage.xml
      WP_MULTISITE=1 phpunit --coverage-clover=coverage.xml
      phpcs --standard=phpcs.xml $(find . -name '*.php')
      phpmd src,tests text ./phpmd.xml
    fi

after_success:
 - bash <(curl -s https://codecov.io/bash)
 